[package]
name = "jwt-cli"
version = "2.2.0"
authors = ["Mike Engel <mike@mike-engel.com>", "Corey McGregor <https://github.com/shousper>", "Aaron Schaef <https://github.com/atschaef>"]

[[bin]]
name = "jwt"
path = "src/main.rs"
test = true

[dependencies]
clap = "2"
jsonwebtoken = "5"
term-painter = "0.2"
serde = "1"
serde_derive = "1"
serde_json = "1"
chrono = "0.4"
